server:
  port: 8090

spring:
  main:
    web-application-type: none
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://117.72.171.32:5432/ai-rag-knowledge
    type: com.zaxxer.hikari.HikariDataSource
  ai:
    openai:
      base-url: https://apis.itedus.cn
      api-key: sk-iMFxb2kbrVSwz6vj7c602dA5E825420bB448098996B19272
      embedding-model: text-embedding-ada-002
      embedding:
        options:
          num-batch: 1536
    ollama:
      base-url: http://117.72.171.32:11434
      mode:
      embedding-model: nomic-embed-text
      embedding:
        options:
          num-batch: 768

logging:
  level:
    root: info
  config: classpath:logback-spring.xml